config/routes.rb
Sapp::Application.routes.draw do
  resources :prospects
  root :to => 'prospects#index'

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prospects }
    end
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
    @prospect = Prospect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prospect }
    end
  end

  # GET /prospects/new
  # GET /prospects/new.json
  def new
    @prospect = Prospect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prospect }
    end
  end

  # GET /prospects/1/edit
  def edit
    @prospect = Prospect.find(params[:id])
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(params[:prospect])

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'Prospect was successfully created.' }
        format.json { render json: @prospect, status: :created, location: @prospect }
      else
        format.html { render action: "new" }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prospects/1
  # PUT /prospects/1.json
  def update
    @prospect = Prospect.find(params[:id])

    respond_to do |format|
      if @prospect.update_attributes(params[:prospect])
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect = Prospect.find(params[:id])
    @prospect.destroy

    respond_to do |format|
      format.html { redirect_to prospects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/layouts/_navbar_sidebar.html.erb
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav slimscrollsidebar">
        <div class="sidebar-head">
            <h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span class="hide-menu">Navigation</span></h3>
        </div>
        <ul class="nav" id="side-menu">
            <li style="padding: 70px 0 0;">
                <a href="index.html" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i>Dashboard</a>
            </li>
            <li>
                <a href="profile.html" class="waves-effect"><i class="fa fa-user fa-fw" aria-hidden="true"></i>Profile</a>
            </li>
            <li>
                <a href="basic-table.html" class="waves-effect"><i class="fa fa-table fa-fw" aria-hidden="true"></i>Basic Table</a>
            </li>
            <li>
                <a href="fontawesome.html" class="waves-effect"><i class="fa fa-font fa-fw" aria-hidden="true"></i>Icons</a>
            </li>
            <li>
                <a href="map-google.html" class="waves-effect"><i class="fa fa-globe fa-fw" aria-hidden="true"></i>Google Map</a>
            </li>
            <li>
                <a href="blank.html" class="waves-effect"><i class="fa fa-columns fa-fw" aria-hidden="true"></i>Blank Page</a>
            </li>
            <li>
                <a href="404.html" class="waves-effect"><i class="fa fa-info-circle fa-fw" aria-hidden="true"></i>Error 404</a>
            </li>

        </ul>
        <div class="center p-20">
             <a href="https://wrappixel.com/templates/ampleadmin/" target="_blank" class="btn btn-danger btn-block waves-effect waves-light">Upgrade to Pro</a>
         </div>
    </div>
    
</div>
<!-- ============================================================== -->
<!-- End Left Sidebar -->
<!-- ============================================================== -->

app/views/layouts/_navbar_top.html.erb
<!-- ============================================================== -->
<!-- Topbar header - style you can find in pages.scss -->
<!-- ============================================================== -->
<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <div class="top-left-part">
            <!-- Logo -->
            <a class="logo" href="index.html">
                <!-- Logo icon image, you can use font-icon also --><b>
                <!--This is dark logo icon--><img src="../plugins/images/admin-logo.png" alt="home" class="dark-logo" /><!--This is light logo icon--><img src="../plugins/images/admin-logo-dark.png" alt="home" class="light-logo" />
             </b>
                <!-- Logo text image you can use text also --><span class="hidden-xs">
                <!--This is dark logo text--><img src="../plugins/images/admin-text.png" alt="home" class="dark-logo" /><!--This is light logo text--><img src="../plugins/images/admin-text-dark.png" alt="home" class="light-logo" />
             </span> </a>
        </div>
        <!-- /Logo -->
        <ul class="nav navbar-top-links navbar-right pull-right">
            <li>
                <form role="search" class="app-search hidden-sm hidden-xs m-r-10">
                    <input type="text" placeholder="Search..." class="form-control"> <a href=""><i class="fa fa-search"></i></a> </form>
            </li>
            <li>
                <a class="profile-pic" href="#"> <img src="../plugins/images/users/varun.jpg" alt="user-img" width="36" class="img-circle"><b class="hidden-xs">Steave</b></a>
            </li>
        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
</nav>
<!-- End Top Navigation -->

app/views/layouts/_prospect.html.erb
<!-- partial for showing contacts -->

<h3 class="box-title">Recent Contacts</h3>
  	<div class="table-responsive">
      	<table class="table">
          	<thead>
              	<tr>
                  	<th>NAME</th>
                  	<th>EMAIL</th>
                      <th></th>
                      <th></th>
                      <th></th>
                </tr>
            </thead>
        <tbody>

			<tr>
			  <td><%= link_to prospect.name, prospect %></td>
			  <td><%= prospect.email %></td>
			  <td><%= link_to 'Show', prospect %></td>
			  <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
			  <td><%= link_to 'Delete', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
        </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class = "fix-header">
<div id = "wrapper">
<%= render 'layouts/navbar_top' %>
<%= render 'layouts/navbar_sidebar' %>

<%= yield %>

</div>

</body>
</html>

app/views/prospects/_form.html.erb
<%= form_for(@prospect) do |f| %>
  <% if @prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% @prospect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prospects/_prospect.html.erb
<!-- partial for showing prospect info -->
<tr>
  <td><%= link_to prospect.name, prospect %></td>
  <td><%= prospect.email %></td>
  <td><%= link_to 'Show', prospect %></td>
  <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
  <td><%= link_to 'Delete', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>       

app/views/prospects/_show_contacts.html.erb
<!-- show prospects -->

<h3 class="box-title">Recent Contacts</h3>
  	<div class="table-responsive">
      	<table class="table">
          	<thead>
              	<tr>
                  	<th>NAME</th>
                  	<th>EMAIL</th>
                      <th></th>
                      <th></th>
                      <th></th>
                </tr>
            </thead>
        <tbody>
        	<%= render prospects %>
        </tbody>
    </table>
</div>

app/views/prospects/edit.html.erb
<h1>Editing prospect</h1>

<%= render 'form' %>

<%= link_to 'Show', @prospect %> |
<%= link_to 'Back', prospects_path %>

app/views/prospects/index.html.erb
<!-- start -->

<div id="page-wrapper">
  <div class="container-fluid">
        
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Dashboard</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="#">Dashboard</a></li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>

  <!-- /.row -->

  <!-- ============================================================== -->
  <!-- table -->
  <!-- ============================================================== -->
    <div class="row">
      <div class="col-md-12 col-lg-12 col-sm-12">
          <div class="white-box">
              <div class="col-md-3 col-sm-4 col-xs-6 pull-right">
                  <select class="form-control pull-right row b-none">
                      <option>March 2017</option>
                      <option>April 2017</option>
                      <option>May 2017</option>
                      <option>June 2017</option>
                      <option>July 2017</option>
                  </select>
              </div>
              <%= render 'show_contacts', prospects: @prospects %>
              <%= link_to 'New Prospect', new_prospect_path, class: 'btn btn-success' %>
          </div>
      </div>
    </div>

  </div>
</div>

app/views/prospects/new.html.erb
<h1>New prospect</h1>

<%= render 'form' %>

<%= link_to 'Back', prospects_path %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @prospect.name %>
</p>

<p>
  <b>Email:</b>
  <%= @prospect.email %>
</p>


<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>